### ISSUE TITLE
clms_global_lst_5km_v2_hourly_netcdf - Too many request 

### ISSUE THREAD

**Issue by Berhinj** [VITObelgium/terracatalogueclient#5]
I'm using this terracatalog to get "clms_global_lst_5km_v2_hourly_netcdf" (great work on this btw) but the server hosting the data is limiting the download speed but raising "Too many requests from your IP" then I have to wait few seconds to try again.

Is there a way for me to get the data faster? Credentials for the API or s3 paths?

This data hosting/dissimination is founded by Copernicus program right? So I guess faster data access has been thought out right? Did I miss it from the documentation?

**Comment by StijnCaerts** [comment]
We're still working on faster data access. 
To improve the compatibility with the rate-limited download server, we added retry functionality with a back-off period to the client. So the download function should no longer fail on the first attempt.
This feature is released in version 0.1.17.

**Comment by StijnCaerts** [comment]
The rate-limiting has been adjusted to allow more requests, throughput will be further improved in a later stage.
